"""Initial schema with all core models

Revision ID: 314bc1528464
Revises: 
Create Date: 2026-09-02 11:34:04.073842

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '314bc1528464'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbp_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('commercial_registration', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_companies_tenant_id'), 'dbp_companies', ['tenant_id'], unique=False)
    op.create_table('dbp_currencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_currencies_tenant_id'), 'dbp_currencies', ['tenant_id'], unique=False)
    op.create_table('dbp_dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=100), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_dashboards_code'), 'dbp_dashboards', ['code'], unique=False)
    op.create_index(op.f('ix_dbp_dashboards_tenant_id'), 'dbp_dashboards', ['tenant_id'], unique=False)
    op.create_table('dbp_data_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_data_jobs_code'), 'dbp_data_jobs', ['code'], unique=False)
    op.create_index(op.f('ix_dbp_data_jobs_entity_code'), 'dbp_data_jobs', ['entity_code'], unique=False)
    op.create_index(op.f('ix_dbp_data_jobs_tenant_id'), 'dbp_data_jobs', ['tenant_id'], unique=False)
    op.create_table('dbp_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('faculty', sa.String(length=50), nullable=False),
    sa.Column('table_mapping', sa.String(length=100), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('metadata_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_entities_code'), 'dbp_entities', ['code'], unique=True)
    op.create_index(op.f('ix_dbp_entities_tenant_id'), 'dbp_entities', ['tenant_id'], unique=False)
    op.create_table('dbp_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_events_entity_code'), 'dbp_events', ['entity_code'], unique=False)
    op.create_index(op.f('ix_dbp_events_event_type'), 'dbp_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_dbp_events_tenant_id'), 'dbp_events', ['tenant_id'], unique=False)
    op.create_table('dbp_kpis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('group_by', sa.String(length=100), nullable=True),
    sa.Column('date_field', sa.String(length=100), nullable=True),
    sa.Column('date_range', sa.String(length=20), nullable=True),
    sa.Column('format_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_kpis_code'), 'dbp_kpis', ['code'], unique=False)
    op.create_index(op.f('ix_dbp_kpis_tenant_id'), 'dbp_kpis', ['tenant_id'], unique=False)
    op.create_table('dbp_notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_notification_preferences_tenant_id'), 'dbp_notification_preferences', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dbp_notification_preferences_user_id'), 'dbp_notification_preferences', ['user_id'], unique=False)
    op.create_table('dbp_notification_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title_template', sa.String(length=500), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_notification_templates_code'), 'dbp_notification_templates', ['code'], unique=False)
    op.create_index(op.f('ix_dbp_notification_templates_event_type'), 'dbp_notification_templates', ['event_type'], unique=False)
    op.create_index(op.f('ix_dbp_notification_templates_tenant_id'), 'dbp_notification_templates', ['tenant_id'], unique=False)
    op.create_table('dbp_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_notifications_channel'), 'dbp_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_dbp_notifications_is_read'), 'dbp_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_dbp_notifications_notification_type'), 'dbp_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_dbp_notifications_tenant_id'), 'dbp_notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dbp_notifications_user_id'), 'dbp_notifications', ['user_id'], unique=False)
    op.create_table('dbp_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('custom_headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_dbp_webhooks_entity_code'), 'dbp_webhooks', ['entity_code'], unique=False)
    op.create_index(op.f('ix_dbp_webhooks_tenant_id'), 'dbp_webhooks', ['tenant_id'], unique=False)
    op.create_table('dbp_workflow_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('escalation_hours', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_workflow_definitions_code'), 'dbp_workflow_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_dbp_workflow_definitions_entity_code'), 'dbp_workflow_definitions', ['entity_code'], unique=False)
    op.create_index(op.f('ix_dbp_workflow_definitions_tenant_id'), 'dbp_workflow_definitions', ['tenant_id'], unique=False)
    op.create_table('dbp_branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['dbp_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_branches_company_id'), 'dbp_branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_dbp_branches_tenant_id'), 'dbp_branches', ['tenant_id'], unique=False)
    op.create_table('dbp_cost_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('budget_amount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['dbp_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dbp_cost_centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_cost_centers_company_id'), 'dbp_cost_centers', ['company_id'], unique=False)
    op.create_index(op.f('ix_dbp_cost_centers_tenant_id'), 'dbp_cost_centers', ['tenant_id'], unique=False)
    op.create_table('dbp_dashboard_widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('query_config', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dbp_dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_dashboard_widgets_dashboard_id'), 'dbp_dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_table('dbp_entity_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_snapshot', sa.JSON(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['dbp_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_entity_versions_entity_id'), 'dbp_entity_versions', ['entity_id'], unique=False)
    op.create_table('dbp_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label_en', sa.String(length=255), nullable=True),
    sa.Column('label_ar', sa.String(length=255), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('ui_config', sa.JSON(), nullable=True),
    sa.Column('enum_values', sa.JSON(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('writable_roles', sa.JSON(), nullable=True),
    sa.Column('visible_roles', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['dbp_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_fields_entity_id'), 'dbp_fields', ['entity_id'], unique=False)
    op.create_table('dbp_fiscal_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['dbp_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_fiscal_years_company_id'), 'dbp_fiscal_years', ['company_id'], unique=False)
    op.create_index(op.f('ix_dbp_fiscal_years_tenant_id'), 'dbp_fiscal_years', ['tenant_id'], unique=False)
    op.create_table('dbp_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('target_entity_code', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('source_column', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('lookup_field', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('tenant_scope', sa.Boolean(), nullable=True),
    sa.Column('on_delete', sa.String(length=20), nullable=True),
    sa.Column('junction_table', sa.String(length=100), nullable=True),
    sa.Column('junction_source_col', sa.String(length=100), nullable=True),
    sa.Column('junction_target_col', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['dbp_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_relationships_entity_id'), 'dbp_relationships', ['entity_id'], unique=False)
    op.create_table('dbp_row_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('filter_column', sa.String(length=100), nullable=False),
    sa.Column('filter_type', sa.String(length=20), nullable=False),
    sa.Column('filter_value', sa.String(length=500), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['dbp_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_row_rules_entity_id'), 'dbp_row_rules', ['entity_id'], unique=False)
    op.create_table('dbp_validation_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_code', sa.String(length=100), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('condition_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['dbp_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_validation_rules_entity_id'), 'dbp_validation_rules', ['entity_id'], unique=False)
    op.create_index(op.f('ix_dbp_validation_rules_field_code'), 'dbp_validation_rules', ['field_code'], unique=False)
    op.create_index(op.f('ix_dbp_validation_rules_rule_type'), 'dbp_validation_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_dbp_validation_rules_tenant_id'), 'dbp_validation_rules', ['tenant_id'], unique=False)
    op.create_table('dbp_webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_response_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['dbp_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['dbp_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_webhook_deliveries_status'), 'dbp_webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_dbp_webhook_deliveries_webhook_id'), 'dbp_webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('dbp_workflow_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('state_type', sa.String(length=20), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['dbp_workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_workflow_states_workflow_id'), 'dbp_workflow_states', ['workflow_id'], unique=False)
    op.create_table('dbp_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('cost_center_id', sa.String(length=36), nullable=True),
    sa.Column('manager_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['dbp_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['dbp_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dbp_departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_departments_company_id'), 'dbp_departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_dbp_departments_tenant_id'), 'dbp_departments', ['tenant_id'], unique=False)
    op.create_table('dbp_workflow_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('current_state_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wf_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['dbp_workflow_states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['dbp_workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_workflow_instances_record_id'), 'dbp_workflow_instances', ['record_id'], unique=False)
    op.create_index(op.f('ix_dbp_workflow_instances_status'), 'dbp_workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_dbp_workflow_instances_tenant_id'), 'dbp_workflow_instances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dbp_workflow_instances_workflow_id'), 'dbp_workflow_instances', ['workflow_id'], unique=False)
    op.create_table('dbp_workflow_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('from_state_id', sa.String(length=36), nullable=False),
    sa.Column('to_state_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_state_id'], ['dbp_workflow_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_state_id'], ['dbp_workflow_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['dbp_workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_workflow_transitions_workflow_id'), 'dbp_workflow_transitions', ['workflow_id'], unique=False)
    op.create_table('dbp_workflow_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('transition_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_state', sa.String(length=100), nullable=True),
    sa.Column('to_state', sa.String(length=100), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['dbp_workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transition_id'], ['dbp_workflow_transitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbp_workflow_actions_instance_id'), 'dbp_workflow_actions', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dbp_workflow_actions_instance_id'), table_name='dbp_workflow_actions')
    op.drop_table('dbp_workflow_actions')
    op.drop_index(op.f('ix_dbp_workflow_transitions_workflow_id'), table_name='dbp_workflow_transitions')
    op.drop_table('dbp_workflow_transitions')
    op.drop_index(op.f('ix_dbp_workflow_instances_workflow_id'), table_name='dbp_workflow_instances')
    op.drop_index(op.f('ix_dbp_workflow_instances_tenant_id'), table_name='dbp_workflow_instances')
    op.drop_index(op.f('ix_dbp_workflow_instances_status'), table_name='dbp_workflow_instances')
    op.drop_index(op.f('ix_dbp_workflow_instances_record_id'), table_name='dbp_workflow_instances')
    op.drop_table('dbp_workflow_instances')
    op.drop_index(op.f('ix_dbp_departments_tenant_id'), table_name='dbp_departments')
    op.drop_index(op.f('ix_dbp_departments_company_id'), table_name='dbp_departments')
    op.drop_table('dbp_departments')
    op.drop_index(op.f('ix_dbp_workflow_states_workflow_id'), table_name='dbp_workflow_states')
    op.drop_table('dbp_workflow_states')
    op.drop_index(op.f('ix_dbp_webhook_deliveries_webhook_id'), table_name='dbp_webhook_deliveries')
    op.drop_index(op.f('ix_dbp_webhook_deliveries_status'), table_name='dbp_webhook_deliveries')
    op.drop_table('dbp_webhook_deliveries')
    op.drop_index(op.f('ix_dbp_validation_rules_tenant_id'), table_name='dbp_validation_rules')
    op.drop_index(op.f('ix_dbp_validation_rules_rule_type'), table_name='dbp_validation_rules')
    op.drop_index(op.f('ix_dbp_validation_rules_field_code'), table_name='dbp_validation_rules')
    op.drop_index(op.f('ix_dbp_validation_rules_entity_id'), table_name='dbp_validation_rules')
    op.drop_table('dbp_validation_rules')
    op.drop_index(op.f('ix_dbp_row_rules_entity_id'), table_name='dbp_row_rules')
    op.drop_table('dbp_row_rules')
    op.drop_index(op.f('ix_dbp_relationships_entity_id'), table_name='dbp_relationships')
    op.drop_table('dbp_relationships')
    op.drop_index(op.f('ix_dbp_fiscal_years_tenant_id'), table_name='dbp_fiscal_years')
    op.drop_index(op.f('ix_dbp_fiscal_years_company_id'), table_name='dbp_fiscal_years')
    op.drop_table('dbp_fiscal_years')
    op.drop_index(op.f('ix_dbp_fields_entity_id'), table_name='dbp_fields')
    op.drop_table('dbp_fields')
    op.drop_index(op.f('ix_dbp_entity_versions_entity_id'), table_name='dbp_entity_versions')
    op.drop_table('dbp_entity_versions')
    op.drop_index(op.f('ix_dbp_dashboard_widgets_dashboard_id'), table_name='dbp_dashboard_widgets')
    op.drop_table('dbp_dashboard_widgets')
    op.drop_index(op.f('ix_dbp_cost_centers_tenant_id'), table_name='dbp_cost_centers')
    op.drop_index(op.f('ix_dbp_cost_centers_company_id'), table_name='dbp_cost_centers')
    op.drop_table('dbp_cost_centers')
    op.drop_index(op.f('ix_dbp_branches_tenant_id'), table_name='dbp_branches')
    op.drop_index(op.f('ix_dbp_branches_company_id'), table_name='dbp_branches')
    op.drop_table('dbp_branches')
    op.drop_index(op.f('ix_dbp_workflow_definitions_tenant_id'), table_name='dbp_workflow_definitions')
    op.drop_index(op.f('ix_dbp_workflow_definitions_entity_code'), table_name='dbp_workflow_definitions')
    op.drop_index(op.f('ix_dbp_workflow_definitions_code'), table_name='dbp_workflow_definitions')
    op.drop_table('dbp_workflow_definitions')
    op.drop_index(op.f('ix_dbp_webhooks_tenant_id'), table_name='dbp_webhooks')
    op.drop_index(op.f('ix_dbp_webhooks_entity_code'), table_name='dbp_webhooks')
    op.drop_table('dbp_webhooks')
    op.drop_index(op.f('ix_dbp_notifications_user_id'), table_name='dbp_notifications')
    op.drop_index(op.f('ix_dbp_notifications_tenant_id'), table_name='dbp_notifications')
    op.drop_index(op.f('ix_dbp_notifications_notification_type'), table_name='dbp_notifications')
    op.drop_index(op.f('ix_dbp_notifications_is_read'), table_name='dbp_notifications')
    op.drop_index(op.f('ix_dbp_notifications_channel'), table_name='dbp_notifications')
    op.drop_table('dbp_notifications')
    op.drop_index(op.f('ix_dbp_notification_templates_tenant_id'), table_name='dbp_notification_templates')
    op.drop_index(op.f('ix_dbp_notification_templates_event_type'), table_name='dbp_notification_templates')
    op.drop_index(op.f('ix_dbp_notification_templates_code'), table_name='dbp_notification_templates')
    op.drop_table('dbp_notification_templates')
    op.drop_index(op.f('ix_dbp_notification_preferences_user_id'), table_name='dbp_notification_preferences')
    op.drop_index(op.f('ix_dbp_notification_preferences_tenant_id'), table_name='dbp_notification_preferences')
    op.drop_table('dbp_notification_preferences')
    op.drop_index(op.f('ix_dbp_kpis_tenant_id'), table_name='dbp_kpis')
    op.drop_index(op.f('ix_dbp_kpis_code'), table_name='dbp_kpis')
    op.drop_table('dbp_kpis')
    op.drop_index(op.f('ix_dbp_events_tenant_id'), table_name='dbp_events')
    op.drop_index(op.f('ix_dbp_events_event_type'), table_name='dbp_events')
    op.drop_index(op.f('ix_dbp_events_entity_code'), table_name='dbp_events')
    op.drop_table('dbp_events')
    op.drop_index(op.f('ix_dbp_entities_tenant_id'), table_name='dbp_entities')
    op.drop_index(op.f('ix_dbp_entities_code'), table_name='dbp_entities')
    op.drop_table('dbp_entities')
    op.drop_index(op.f('ix_dbp_data_jobs_tenant_id'), table_name='dbp_data_jobs')
    op.drop_index(op.f('ix_dbp_data_jobs_entity_code'), table_name='dbp_data_jobs')
    op.drop_index(op.f('ix_dbp_data_jobs_code'), table_name='dbp_data_jobs')
    op.drop_table('dbp_data_jobs')
    op.drop_index(op.f('ix_dbp_dashboards_tenant_id'), table_name='dbp_dashboards')
    op.drop_index(op.f('ix_dbp_dashboards_code'), table_name='dbp_dashboards')
    op.drop_table('dbp_dashboards')
    op.drop_index(op.f('ix_dbp_currencies_tenant_id'), table_name='dbp_currencies')
    op.drop_table('dbp_currencies')
    op.drop_index(op.f('ix_dbp_companies_tenant_id'), table_name='dbp_companies')
    op.drop_table('dbp_companies')
    # ### end Alembic commands ###
