"""
EOS PDF Service — Invoice/Quote/Order Generation
Generates professional HTML-based documents (PDF-ready)
"""
from datetime import datetime, timezone


class PDFService:
    def __init__(self):
        self.currency = "SAR"
        self.company_name = "EOS Platform"
        self.company_vat = "300000000000003"

    def _header(self, doc_type, doc_number, doc_date):
        return f"""
        <div style="display:flex; justify-content:space-between; margin-bottom:30px;">
            <div>
                <h1 style="color:#1890ff; margin:0;">EOS Platform</h1>
                <p style="color:#666; margin:5px 0;">VAT: {self.company_vat}</p>
            </div>
            <div style="text-align:right;">
                <h2 style="color:#333; margin:0;">{doc_type}</h2>
                <p style="margin:5px 0;"><strong>Number:</strong> {doc_number}</p>
                <p style="margin:5px 0;"><strong>Date:</strong> {doc_date}</p>
            </div>
        </div>
        """

    def _party_block(self, title, name, email="", address=""):
        return f"""
        <div style="margin-bottom:20px;">
            <h3 style="color:#1890ff; border-bottom:2px solid #1890ff; padding-bottom:5px;">{title}</h3>
            <p><strong>{name}</strong></p>
            <p>{email}</p>
            <p>{address}</p>
        </div>
        """

    def _items_table(self, items, qty_label="Qty", price_label="Unit Price", total_label="Total"):
        rows = ""
        for i, item in enumerate(items, 1):
            bg = "#f5f5f5" if i % 2 == 0 else "#fff"
            rows += f"""
            <tr style="background:{bg};">
                <td style="padding:10px; border:1px solid #ddd;">{i}</td>
                <td style="padding:10px; border:1px solid #ddd;">{item.get('name','')}</td>
                <td style="padding:10px; border:1px solid #ddd; text-align:center;">{item.get('qty',0)}</td>
                <td style="padding:10px; border:1px solid #ddd; text-align:right;">{item.get('unit_price',0):,.2f} {self.currency}</td>
                <td style="padding:10px; border:1px solid #ddd; text-align:right;">{item.get('total',0):,.2f} {self.currency}</td>
            </tr>
            """
        return f"""
        <table style="width:100%; border-collapse:collapse; margin:20px 0;">
            <thead>
                <tr style="background:#1890ff; color:white;">
                    <th style="padding:10px; border:1px solid #ddd;">#</th>
                    <th style="padding:10px; border:1px solid #ddd;">Item</th>
                    <th style="padding:10px; border:1px solid #ddd;">{qty_label}</th>
                    <th style="padding:10px; border:1px solid #ddd;">{price_label}</th>
                    <th style="padding:10px; border:1px solid #ddd;">{total_label}</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
        """

    def _totals(self, subtotal, vat_rate=15, discount=0):
        vat = subtotal * vat_rate / 100
        total = subtotal + vat - discount
        return f"""
        <div style="text-align:right; margin:20px 0;">
            <p>Subtotal: <strong>{subtotal:,.2f} {self.currency}</strong></p>
            <p>VAT ({vat_rate}%): <strong>{vat:,.2f} {self.currency}</strong></p>
            <p style="font-size:18px; color:#1890ff;">Total: <strong>{total:,.2f} {self.currency}</strong></p>
        </div>
        """

    def _footer(self):
        return f"""
        <div style="margin-top:40px; padding-top:20px; border-top:2px solid #1890ff; text-align:center; color:#666;">
            <p>Thank you for your business!</p>
            <p style="font-size:12px;">Generated by EOS Platform — {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M')}</p>
        </div>
        """

    def generate_invoice(self, invoice_data):
        items = invoice_data.get("items", [])
        subtotal = sum(i.get("total", i.get("qty", 0) * i.get("unit_price", 0)) for i in items)
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial; max-width:800px; margin:0 auto; padding:20px;">
    {self._header("TAX INVOICE", invoice_data.get("invoice_number","INV-001"), invoice_data.get("date", datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")))}
    {self._party_block("Bill To", invoice_data.get("customer_name","Customer"), invoice_data.get("customer_email",""))}
    {self._items_table(items)}
    {self._totals(subtotal)}
    {self._footer()}
</body></html>"""
        return {"html": html, "doc_type": "invoice", "number": invoice_data.get("invoice_number", "INV-001")}

    def generate_quote(self, quote_data):
        items = quote_data.get("items", [])
        subtotal = sum(i.get("total", i.get("qty", 0) * i.get("unit_price", 0)) for i in items)
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial; max-width:800px; margin:0 auto; padding:20px;">
    {self._header("QUOTATION", quote_data.get("quote_number","QT-001"), quote_data.get("date", datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")))}
    {self._party_block("Prepared For", quote_data.get("customer_name","Customer"), quote_data.get("customer_email",""))}
    {self._items_table(items)}
    {self._totals(subtotal)}
    <div style="background:#fff7e6; border:1px solid #ffd591; padding:15px; border-radius:4px; margin:20px 0;">
        <p><strong>Valid until:</strong> {quote_data.get("valid_until","30 days")}</p>
        <p><strong>Payment Terms:</strong> {quote_data.get("payment_terms","Net 30")}</p>
    </div>
    {self._footer()}
</body></html>"""
        return {"html": html, "doc_type": "quote", "number": quote_data.get("quote_number", "QT-001")}

    def generate_sales_order(self, order_data):
        items = order_data.get("items", [])
        subtotal = sum(i.get("total", i.get("qty", 0) * i.get("unit_price", 0)) for i in items)
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial; max-width:800px; margin:0 auto; padding:20px;">
    {self._header("SALES ORDER", order_data.get("order_number","SO-001"), order_data.get("date", datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")))}
    {self._party_block("Customer", order_data.get("customer_name","Customer"), order_data.get("customer_email",""))}
    {self._items_table(items)}
    {self._totals(subtotal)}
    {self._footer()}
</body></html>"""
        return {"html": html, "doc_type": "sales_order", "number": order_data.get("order_number", "SO-001")}

    def generate_purchase_order(self, po_data):
        items = po_data.get("items", [])
        subtotal = sum(i.get("total", i.get("qty", 0) * i.get("unit_price", 0)) for i in items)
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial; max-width:800px; margin:0 auto; padding:20px;">
    {self._header("PURCHASE ORDER", po_data.get("po_number","PO-001"), po_data.get("date", datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")))}
    {self._party_block("Supplier", po_data.get("supplier_name","Supplier"), po_data.get("supplier_email",""))}
    {self._items_table(items, qty_label="Qty", price_label="Unit Cost", total_label="Total Cost")}
    {self._totals(subtotal)}
    {self._footer()}
</body></html>"""
        return {"html": html, "doc_type": "purchase_order", "number": po_data.get("po_number", "PO-001")}
