import { useEffect, useState } from 'react';
import { FiActivity, FiArrowRight, FiBarChart2, FiBell, FiBox, FiChevronDown, FiFileText, FiGlobe, FiHome, FiMenu, FiPlus, FiSearch, FiSettings, FiUsers } from 'react-icons/fi';
import EosDataGrid from './components/EosDataGrid';
import EosDynamicForm from './components/EosDynamicForm';
import EosOnboardingWizard from './components/EosOnboardingWizard';
import { invoicesAPI, ordersAPI, reportsAPI } from './services/api';
import './styles/eos-app.css';

type Language = 'ar' | 'en';
type Translation = { home:string;customers:string;inventory:string;sales:string;reports:string;settings:string;search:string;welcome:string;subtitle:string;revenue:string;orders:string;receivables:string;tasks:string;newCustomer:string;viewAll:string;active:string;pending:string;onboarding:string;connected:string;switchLanguage:string };
const translations: Record<Language, Translation> = { ar:{home:'الرئيسية',customers:'العملاء',inventory:'المخزون',sales:'المبيعات',reports:'التقارير',settings:'الإعدادات',search:'بحث سريع',welcome:'مرحباً بك في EOS',subtitle:'منصة أعمال ذكية تبني مساحة العمل من طبيعة نشاطك.',revenue:'إيرادات الشهر',orders:'الفواتير',receivables:'المستحقات',tasks:'تنبيهات تحتاج انتباهك',newCustomer:'عميل جديد',viewAll:'عرض الكل',active:'نشط',pending:'قيد المراجعة',onboarding:'ابدأ بناء نظامك',connected:'متصل',switchLanguage:'English'}, en:{home:'Home',customers:'Customers',inventory:'Inventory',sales:'Sales',reports:'Reports',settings:'Settings',search:'Quick search',welcome:'Welcome to EOS',subtitle:'An intelligent business platform that builds your workspace around your business.',revenue:'Monthly revenue',orders:'Invoices',receivables:'Receivables',tasks:'Alerts needing attention',newCustomer:'New customer',viewAll:'View all',active:'Active',pending:'In review',onboarding:'Build your ERP',connected:'Connected',switchLanguage:'العربية'} };

export default function App() {
  const [lang, setLang] = useState<Language>('ar'); const [page, setPage] = useState('home'); const [builder, setBuilder] = useState(false); const t = translations[lang];
  const nav = [[t.home,'home',FiHome],[t.customers,'customers',FiUsers],[t.inventory,'inventory',FiBox],[t.sales,'sales',FiFileText],[t.reports,'reports',FiBarChart2],[t.settings,'settings',FiSettings]] as const;
  return <div className="eos-app" dir={lang === 'ar' ? 'rtl' : 'ltr'}><aside className="eos-sidebar"><div className="eos-brand"><span className="eos-logo">E</span><span>EOS</span></div><button className="eos-create" onClick={() => setBuilder(true)}><FiPlus/><span>{t.onboarding}</span></button><nav>{nav.map(([label,key,Icon]) => <button key={key} className={`eos-nav-item ${page===key?'is-active':''}`} onClick={() => { setBuilder(false); setPage(key); }}><Icon/><span>{label}</span></button>)}</nav><div className="eos-sidebar-footer"><span className="eos-status-dot"/>{t.connected}</div></aside><main className="eos-main"><header className="eos-topbar"><button className="eos-icon-button eos-mobile-menu" aria-label="Menu"><FiMenu/></button><div className="eos-search"><FiSearch/><input aria-label={t.search} placeholder={t.search}/></div><div className="eos-top-actions"><button className="eos-language" onClick={() => setLang(lang==='ar'?'en':'ar')}><FiGlobe/> {t.switchLanguage}</button><button className="eos-icon-button" aria-label={lang==='ar'?'الإشعارات':'Notifications'}><FiBell/></button><div className="eos-avatar">EOS</div></div></header><div className="eos-content">{builder?<EosOnboardingWizard language={lang} onBack={() => setBuilder(false)} onComplete={() => setBuilder(false)}/>:page==='customers'?<Customers t={t} language={lang}/>:page==='inventory'?<Inventory t={t} language={lang}/>:page==='sales'?<Sales language={lang}/>:page==='reports'?<Reports t={t} language={lang}/>:page==='settings'?<Settings t={t}/>:<Dashboard t={t} onBuild={() => setBuilder(true)} language={lang}/>}</div></main></div>;
}

function Dashboard({t,onBuild,language}:{t:Translation;onBuild:()=>void;language:Language}) {
  const [summary,setSummary]=useState<any>(null); const [sales,setSales]=useState<any>(null); const [inventory,setInventory]=useState<any>(null);
  useEffect(() => { let alive=true; Promise.all([reportsAPI.profitAndLoss(),reportsAPI.sales(),reportsAPI.inventory()]).then(([p,s,i])=>{if(alive){setSummary(p.data?.data);setSales(s.data?.data);setInventory(i.data?.data);}}).catch(()=>{});return()=>{alive=false;}; },[]);
  const revenue=summary?.revenue??0; const invoices=sales?.daily?.reduce((n:number,x:any)=>n+Number(x.count||0),0)??0; const receivables=summary?.receivables??0;
  const cards=[[t.revenue,formatMoney(revenue),summary?`${summary.gross_margin??0}%`:t.connected,FiActivity],[t.orders,String(invoices),sales?`${sales.top_customers?.length??0} ${language==='ar'?'عملاء نشطون':'active customers'}`:t.connected,FiBox],[t.receivables,formatMoney(receivables),`${inventory?.total_items??0} ${language==='ar'?'صنف':'items'}`,FiBarChart2]] as const;
  return <><section className="eos-page-heading"><div><span className="eos-eyebrow">EOS DBP</span><h1>{t.welcome}</h1><p>{t.subtitle}</p></div><button className="eos-primary-button" onClick={onBuild}>{t.onboarding}<FiArrowRight/></button></section><section className="eos-kpi-grid">{cards.map(([label,value,delta,Icon])=><article className="eos-card eos-kpi" key={label}><div className="eos-kpi-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{delta}</small></article>)}</section><section className="eos-dashboard-grid"><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>{language==='ar'?'الأداء':'Performance'}</h2><span>{language==='ar'?'بيانات من محرك التقارير':'Reporting engine data'}</span></div><button className="eos-ghost-button">{language==='ar'?'هذا الشهر':'This month'} <FiChevronDown/></button></div><div className="eos-bars" aria-label={language==='ar'?'اتجاه المبيعات':'Sales trend'}>{(sales?.daily?.slice(-12)||[]).map((x:any,i:number)=><span key={i} style={{height:`${Math.max(8,Math.min(100,Number(x.amount||0)/(Math.max(...(sales?.daily||[]).map((d:any)=>Number(d.amount||0)),1))*100))}%`}}/>)}{!sales?.daily?.length&&<span style={{height:'8%'}}/>}</div></article><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>{t.tasks}</h2><span>{language==='ar'?'مؤشرات من النظام':'System indicators'}</span></div></div><div className="eos-task-list"><div className="eos-task"><span className="eos-task-check">✓</span><div><strong>{language==='ar'?'المستحقات قيد المتابعة':'Receivables are being monitored'}</strong><small>{t.active}</small></div></div><div className="eos-task"><span className="eos-task-check">✓</span><div><strong>{language==='ar'?'المخزون منخفض حسب مستوى إعادة الطلب':'Inventory reorder levels checked'}</strong><small>{inventory?.low_stock_items??0} {language==='ar'?'أصناف':'items'}</small></div></div><div className="eos-task"><span className="eos-task-check">✓</span><div><strong>{language==='ar'?'صافي الربح':'Gross profit'}</strong><small>{formatMoney(summary?.gross_profit??0)}</small></div></div></div></article></section></>;
}

function Customers({t,language}:{t:Translation;language:Language}) { const [formOpen,setFormOpen]=useState(false); return <>{formOpen&&<EosDynamicForm entityCode="customers" language={language} onClose={()=>setFormOpen(false)}/>}<section className="eos-page-heading"><div><span className="eos-eyebrow">customers</span><h1>{t.customers}</h1><p>{language==='ar'?'إدارة العملاء من خلال طبقة Metadata والصلاحيات الخلفية.':'Customer workspace backed by metadata and tenant permissions.'}</p></div><button className="eos-primary-button" onClick={()=>setFormOpen(true)}><FiPlus/> {t.newCustomer}</button></section><EosDataGrid entityCode="customers" language={language}/></>; }
function Inventory({t,language}:{t:Translation;language:Language}) { return <><section className="eos-page-heading"><div><span className="eos-eyebrow">inventory</span><h1>{t.inventory}</h1><p>{language==='ar'?'المخزون الفعلي مع البحث والتصفية.':'Live inventory with search and filtering.'}</p></div></section><EosDataGrid entityCode="items" language={language}/></>; }
function Sales({language}:{language:Language}) { const [orders,setOrders]=useState<any[]>([]); const [invoices,setInvoices]=useState<any[]>([]); const [busy,setBusy]=useState(''); const ar=language==='ar'; const load=()=>Promise.all([ordersAPI.getAll(),invoicesAPI.getAll()]).then(([o,i])=>{setOrders(o.data?.data||[]);setInvoices(i.data?.data||[]);}).catch(()=>{}); useEffect(()=>{load();},[]); const issue=async(id:string)=>{setBusy(id);try{await invoicesAPI.issue(id);await load();}finally{setBusy('');}}; return <><section className="eos-page-heading"><div><span className="eos-eyebrow">sales</span><h1>{ar?'دورة المبيعات':'Sales cycle'}</h1><p>{ar?'أوامر البيع والفواتير والتحصيل مع ترحيل محاسبي مزدوج.':'Orders, invoices and collections with double-entry accounting.'}</p></div></section><section className="eos-dashboard-grid"><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>{ar?'أوامر البيع':'Sales orders'}</h2><span>{orders.length} {ar?'مستند':'documents'}</span></div></div>{orders.length?<div className="eos-task-list">{orders.slice(0,8).map((o:any)=><div className="eos-task" key={o.id}><div><strong>{o.order_number||o.id}</strong><small>{o.customer_name||'—'} · {formatMoney(o.total_amount)} {o.currency_code||''}</small></div><span>{o.status}</span></div>)}</div>:<p>{ar?'لا توجد أوامر بيع بعد.':'No sales orders yet.'}</p>}</article><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>{ar?'الفواتير':'Invoices'}</h2><span>{invoices.length} {ar?'فاتورة':'invoices'}</span></div></div>{invoices.length?<div className="eos-task-list">{invoices.slice(0,8).map((i:any)=><div className="eos-task" key={i.id}><div><strong>{i.invoice_number||i.id}</strong><small>{i.customer_name||'—'} · {formatMoney(i.total_amount+(i.tax_amount||0))}</small></div>{i.status==='draft'?<button className="eos-ghost-button" disabled={busy===i.id} onClick={()=>issue(i.id)}>{busy===i.id?(ar?'جارٍ…':'Issuing…'):(ar?'إصدار':'Issue')}</button>:<span>{i.status}</span>}</div>)}</div>:<p>{ar?'لا توجد فواتير بعد.':'No invoices yet.'}</p>}</article></section></>; }
function Reports({t,language}:{t:Translation;language:Language}) { const [data,setData]=useState<any>(null); useEffect(()=>{reportsAPI.profitAndLoss().then(r=>setData(r.data?.data)).catch(()=>{});},[]); return <><section className="eos-page-heading"><div><span className="eos-eyebrow">reports</span><h1>{t.reports}</h1><p>{language==='ar'?'تقارير مالية وتشغيلية من محرك التقارير الخلفي.':'Financial and operational reports from the backend reporting engine.'}</p></div></section><section className="eos-kpi-grid"><article className="eos-card eos-kpi"><span>{t.revenue}</span><strong>{formatMoney(data?.revenue)}</strong></article><article className="eos-card eos-kpi"><span>{language==='ar'?'المصروفات':'Expenses'}</span><strong>{formatMoney(data?.cost_of_goods)}</strong></article><article className="eos-card eos-kpi"><span>{language==='ar'?'مجمل الربح':'Gross profit'}</span><strong>{formatMoney(data?.gross_profit)}</strong></article></section></>; }
function Settings({t}:{t:Translation}) { return <section className="eos-empty-state eos-card"><FiSettings/><h1>{t.settings}</h1><p>EOS configuration is metadata-driven and tenant-scoped.</p></section>; }
function formatMoney(value:unknown) { return new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(Number(value||0)); }