import { useState } from 'react';
import { FiActivity, FiArrowRight, FiBarChart2, FiBell, FiBox, FiCheckCircle, FiChevronDown, FiGlobe, FiHome, FiMenu, FiPlus, FiSearch, FiSettings, FiUsers } from 'react-icons/fi';
import type { EosEntitySchema, EosFieldSchema } from './design-system';
import './styles/eos-app.css';

type Language = 'ar' | 'en';
type Translation = { home:string; customers:string; inventory:string; reports:string; settings:string; search:string; welcome:string; subtitle:string; revenue:string; orders:string; receivables:string; tasks:string; newCustomer:string; viewAll:string; status:string; customer:string; amount:string; active:string; pending:string; onboarding:string; business:string; generate:string; generated:string; back:string; demo:string; switchLanguage:string };
const translations: Record<Language, Translation> = {
 ar:{home:'الرئيسية',customers:'العملاء',inventory:'المخزون',reports:'التقارير',settings:'الإعدادات',search:'بحث سريع',welcome:'مرحباً بك في EOS',subtitle:'منصة أعمال ذكية تبني مساحة العمل من طبيعة نشاطك.',revenue:'إيرادات الشهر',orders:'الطلبات',receivables:'المستحقات',tasks:'مهام تحتاج انتباهك',newCustomer:'عميل جديد',viewAll:'عرض الكل',status:'الحالة',customer:'العميل',amount:'القيمة',active:'نشط',pending:'قيد المراجعة',onboarding:'ابدأ بناء نظامك',business:'ما طبيعة نشاطك؟',generate:'إنشاء مساحة العمل',generated:'تم تجهيز مساحة العمل',back:'رجوع',demo:'بيانات تجريبية',switchLanguage:'English'},
 en:{home:'Home',customers:'Customers',inventory:'Inventory',reports:'Reports',settings:'Settings',search:'Quick search',welcome:'Welcome to EOS',subtitle:'An intelligent business platform that builds your workspace around your business.',revenue:'Monthly revenue',orders:'Orders',receivables:'Receivables',tasks:'Tasks needing attention',newCustomer:'New customer',viewAll:'View all',status:'Status',customer:'Customer',amount:'Amount',active:'Active',pending:'In review',onboarding:'Build your ERP',business:'What does your business do?',generate:'Generate workspace',generated:'Workspace ready',back:'Back',demo:'Demo data',switchLanguage:'العربية'}
};
const customerFields:EosFieldSchema[]=[{key:'name',label:'Customer name',type:'text',ui:{component:'text',required:true,width:6}},{key:'email',label:'Email',type:'text',ui:{component:'text',width:6}},{key:'phone',label:'Phone',type:'text',ui:{component:'text',width:6}},{key:'status',label:'Status',type:'select',ui:{component:'select',width:6}}];
const customerSchema:EosEntitySchema={key:'customers',label:'Customers',fields:customerFields,permissions:{create:true,read:true,update:true,delete:true}};
export default function App(){const[lang,setLang]=useState<Language>('ar');const[page,setPage]=useState('home');const[builder,setBuilder]=useState(false);const[business,setBusiness]=useState('');const[ready,setReady]=useState(false);const t=translations[lang];const nav=[[t.home,'home',FiHome],[t.customers,'customers',FiUsers],[t.inventory,'inventory',FiBox],[t.reports,'reports',FiBarChart2],[t.settings,'settings',FiSettings]] as const;return <div className="eos-app" dir={lang==='ar'?'rtl':'ltr'}><aside className="eos-sidebar"><div className="eos-brand"><span className="eos-logo">E</span><span>EOS</span></div><button className="eos-create" onClick={()=>setBuilder(true)}><FiPlus/> {t.onboarding}</button><nav>{nav.map(([label,key,Icon])=><button key={key} className={`eos-nav-item ${page===key?'is-active':''}`} onClick={()=>setPage(key)}><Icon/><span>{label}</span></button>)}</nav><div className="eos-sidebar-footer"><span className="eos-status-dot"/>{t.demo}</div></aside><main className="eos-main"><header className="eos-topbar"><button className="eos-icon-button eos-mobile-menu" aria-label="Menu"><FiMenu/></button><div className="eos-search"><FiSearch/><input aria-label={t.search} placeholder={t.search}/></div><div className="eos-top-actions"><button className="eos-language" onClick={()=>setLang(lang==='ar'?'en':'ar')}><FiGlobe/> {t.switchLanguage}</button><button className="eos-icon-button" aria-label="Notifications"><FiBell/><span className="eos-notification-dot"/></button><div className="eos-avatar">CM</div></div></header><div className="eos-content">{builder?<Builder t={t} business={business} setBusiness={setBusiness} ready={ready} setReady={setReady} onBack={()=>setBuilder(false)}/>:page==='customers'?<Customers t={t}/>:<Dashboard t={t} onBuild={()=>setBuilder(true)}/>}</div></main></div>}
function Dashboard({t,onBuild}:{t:Translation;onBuild:()=>void}){const cards=[[t.revenue,'€128,420','+12.8%',FiActivity],[t.orders,'1,284','+8.4%',FiBox],[t.receivables,'€42,760','-3.2%',FiBarChart2]] as const;return <><section className="eos-page-heading"><div><span className="eos-eyebrow">EOS DBP</span><h1>{t.welcome}</h1><p>{t.subtitle}</p></div><button className="eos-primary-button" onClick={onBuild}>{t.onboarding}<FiArrowRight/></button></section><section className="eos-kpi-grid">{cards.map(([label,value,delta,Icon])=><article className="eos-card eos-kpi" key={label}><div className="eos-kpi-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{delta}</small></article>)}</section><section className="eos-dashboard-grid"><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>Performance</h2><span>Last 6 months</span></div><button className="eos-ghost-button">Monthly <FiChevronDown/></button></div><div className="eos-bars" aria-label="Revenue trend">{[44,58,52,72,66,88,79,96,84,100,92,108].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div></article><article className="eos-card eos-chart-card"><div className="eos-card-heading"><div><h2>{t.tasks}</h2><span>4 items</span></div><button className="eos-ghost-button">{t.viewAll}</button></div><div className="eos-task-list">{['Approve purchase order #1042','Invoice INV-2088 is overdue','Stock level below threshold','Monthly close ready'].map((x,i)=><div className="eos-task" key={x}><span className="eos-task-check"><FiCheckCircle/></span><div><strong>{x}</strong><small>{i===3?t.active:t.pending}</small></div></div>)}</div></article></section></>}
function Customers({t}:{t:Translation}){const rows=[['Acme Industries','finance@acme.example','€24,500',t.active],['Northstar Group','ops@northstar.example','€18,200',t.active],['Cedar Trading','hello@cedar.example','€9,840',t.pending],['Atlas Construction','accounts@atlas.example','€7,620',t.active]];return <><section className="eos-page-heading"><div><span className="eos-eyebrow">{customerSchema.key}</span><h1>{t.customers}</h1><p>Metadata-driven entity workspace.</p></div><button className="eos-primary-button"><FiPlus/> {t.newCustomer}</button></section><div className="eos-card eos-table-card"><div className="eos-table-toolbar"><div className="eos-search eos-table-search"><FiSearch/><input placeholder={t.search}/></div><button className="eos-ghost-button">Filters <FiChevronDown/></button></div><div className="eos-table-wrap"><table><thead><tr><th>{t.customer}</th><th>Email</th><th>{t.amount}</th><th>{t.status}</th></tr></thead><tbody>{rows.map(([name,email,amount,status])=><tr key={name}><td><strong>{name}</strong></td><td>{email}</td><td>{amount}</td><td><span className={`eos-pill ${status===t.active?'success':'warning'}`}>{status}</span></td></tr>)}</tbody></table></div><div className="eos-table-footer">Showing 1–4 of 4</div></div></>}
function Builder({t,business,setBusiness,ready,setReady,onBack}:{t:Translation;business:string;setBusiness:(v:string)=>void;ready:boolean;setReady:(v:boolean)=>void;onBack:()=>void}){if(ready)return <section className="eos-onboarding eos-success"><div className="eos-success-icon"><FiCheckCircle/></div><span className="eos-eyebrow">EOS</span><h1>{t.generated}</h1><p>Your workspace includes Sales, Finance, Inventory and a role-based dashboard.</p><div className="eos-generation-grid"><span>✓ Finance</span><span>✓ Sales</span><span>✓ Inventory</span><span>✓ Customers</span></div><button className="eos-primary-button" onClick={onBack}>{t.home}<FiArrowRight/></button></section>;return <section className="eos-onboarding"><button className="eos-back-button" onClick={onBack}>← {t.back}</button><div className="eos-onboarding-inner"><span className="eos-eyebrow">EOS BUSINESS BUILDER</span><h1>{t.onboarding}</h1><p>{t.subtitle}</p><label htmlFor="business">{t.business}</label><textarea id="business" value={business} onChange={e=>setBusiness(e.target.value)} rows={5} placeholder={langPlaceholder(t)}/><div className="eos-suggestions"><button onClick={()=>setBusiness('Real estate development and property management')}>Real estate</button><button onClick={()=>setBusiness('Construction company with projects, procurement and payroll')}>Construction</button><button onClick={()=>setBusiness('Trading and distribution company')}>Trading</button></div><button className="eos-primary-button eos-generate" disabled={!business.trim()} onClick={()=>setReady(true)}>{t.generate}<FiArrowRight/></button><div className="eos-stepper"><span className="is-done">1. Business</span><span>2. Clarify</span><span>3. Generate</span><span>4. Launch</span></div></div></section>}
function langPlaceholder(t:Translation){return t===translations.ar?'مثال: شركة تطوير عقاري تشتري الأراضي وتبني وتبيع الوحدات...':'Example: a construction company managing projects, procurement, payroll and finance...'}
