import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type FieldType = 'text' | 'integer' | 'decimal' | 'boolean' | 'date' | 'uuid' | 'relation';
type PermissionAction = 'create' | 'read' | 'update' | 'delete';
type Permissions = { admin: PermissionAction[]; member: PermissionAction[] };
type Field = { code: string; type: FieldType; required: boolean; nullable: boolean; label?: string | null; target_entity?: string | null };
type Definition = { code: string; name: string; fields: Field[]; permissions?: Permissions };
type Metadata = { id: string; tenant_id: string; definition: Definition; version: number; published: boolean };
type MetadataSummary = { id: string; code: string; name: string; version: number; field_count: number; permissions: Permissions };
type RecordItem = { id: string; data: Record<string, unknown>; version: number };
type LookupItem = { id: string; label: string; data: Record<string, unknown> };
type Session = { access_token: string; user_id: string; tenant_id: string; role: string; expires_in: number };
type FormField = { code: string; type: FieldType; required: boolean; label: string; target_entity?: string };

const API = import.meta.env.VITE_API_URL ?? '/api/v1';
const DEFAULT_ENTITY = import.meta.env.VITE_ENTITY_CODE ?? '';
const TOKEN_KEY = '2to_eos_access_token';

function sessionFromStorage(): Session | null { const token = localStorage.getItem(TOKEN_KEY); return token ? { access_token: token, user_id: '', tenant_id: '', role: '', expires_in: 0 } : null; }

async function api<T>(path: string, token: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`${API}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(init.headers ?? {}) } }); if (!response.ok) throw new Error((await response.text()) || `HTTP ${response.status}`); if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }

function AuthScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [tenantName,setTenantName]=useState(''); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function submit(){setBusy(true);setError(null);try{const path=mode==='login'?'/auth/token':'/auth/register';const body=mode==='login'?{email,password}:{email,password,tenant_name:tenantName};const response=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error((await response.text())||`HTTP ${response.status}`);const data=(await response.json()) as Session;localStorage.setItem(TOKEN_KEY,data.access_token);onAuthenticated(data);}catch(err){setError(err instanceof Error?err.message:'Authentication failed');}finally{setBusy(false);}}
  return <main className="shell auth-shell"><section className="card auth-card"><p className="eyebrow">2TO / EOS</p><h1>{mode==='login'?'Sign in':'Create your workspace'}</h1><p className="muted">Your workspace and permissions come from the signed access token.</p>{error&&<div className="error" role="alert">{error}</div>}<label><span>Email</span><input value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="email"/></label><label><span>Password</span><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='register'&&<label><span>Workspace name</span><input value={tenantName} onChange={(e)=>setTenantName(e.target.value)}/></label>}<button disabled={busy||!email||password.length<(mode==='register'?12:1)||(mode==='register'&&!tenantName)} onClick={()=>void submit()}>{busy?'Working…':mode==='login'?'Sign in':'Create workspace'}</button><button className="secondary" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create a new workspace':'I already have an account'}</button></section></main>;
}

function MetadataStudio({ token, defaultCode, onCreated }: { token:string; defaultCode:string; onCreated:(code:string)=>void }) {
  const [code,setCode]=useState(defaultCode||'new_entity'); const [name,setName]=useState('New Entity'); const [fields,setFields]=useState<FormField[]>([{code:'name',type:'text',required:true,label:'Name'}]); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  function updateField(index:number,patch:Partial<FormField>){setFields((current)=>current.map((field,position)=>position===index?{...field,...patch}:field));}
  async function publish(){setError(null);setMessage(null);try{const created=await api<Metadata>('/metadata/entities',token,{method:'POST',body:JSON.stringify({code,name,fields:fields.map((field)=>({...field,nullable:false}))})});await api(`/metadata/entities/${created.definition.code}/publish`,token,{method:'POST'});setMessage(`Published ${created.definition.code} v${created.version}.`);onCreated(created.definition.code);}catch(err){setError(err instanceof Error?err.message:'Unable to publish metadata');}}
  return <section className="card"><div className="section-head"><div><p className="eyebrow">Metadata Studio</p><h2>Define an entity</h2></div></div>{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}<div className="grid"><label><span>Entity code</span><input value={code} onChange={(e)=>setCode(e.target.value)}/></label><label><span>Display name</span><input value={name} onChange={(e)=>setName(e.target.value)}/></label></div><div className="field-list">{fields.map((field,index)=><div className="field-row" key={`${index}-${field.code}`}><input value={field.code} onChange={(e)=>updateField(index,{code:e.target.value})} aria-label="Field code"/><select value={field.type} onChange={(e)=>updateField(index,{type:e.target.value as FieldType})} aria-label="Field type"><option value="text">Text</option><option value="integer">Integer</option><option value="decimal">Decimal</option><option value="boolean">Boolean</option><option value="date">Date</option><option value="uuid">UUID</option><option value="relation">Relation</option></select><input value={field.label} onChange={(e)=>updateField(index,{label:e.target.value})} aria-label="Field label"/>{field.type==='relation'&&<input value={field.target_entity??''} onChange={(e)=>updateField(index,{target_entity:e.target.value})} placeholder="Target entity" aria-label="Relation target"/>}<label className="inline-check"><input type="checkbox" checked={field.required} onChange={(e)=>updateField(index,{required:e.target.checked})}/> Required</label><button className="danger" onClick={()=>setFields((current)=>current.filter((_,position)=>position!==index))}>Remove</button></div>)}</div><div className="actions"><button className="secondary" onClick={()=>setFields((current)=>[...current,{code:`field_${current.length+1}`,type:'text',required:false,label:`Field ${current.length+1}`}])}>Add field</button><button disabled={!code||!name||fields.length===0} onClick={()=>void publish()}>Publish entity</button></div></section>;
}

function RelationField({token,field,value,onChange}:{token:string;field:Field;value:string;onChange:(value:string)=>void}){const [items,setItems]=useState<LookupItem[]>([]);const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);useEffect(()=>{let active=true;const timer=window.setTimeout(async()=>{if(!field.target_entity)return;setBusy(true);setError(null);try{const suffix=query.trim()?`?q=${encodeURIComponent(query.trim())}&limit=25`:'?limit=25';const data=await api<LookupItem[]>(`/entities/${field.target_entity}/lookup${suffix}`,token);if(active)setItems(data);}catch(err){if(active)setError(err instanceof Error?err.message:'Unable to load choices');}finally{if(active)setBusy(false);}},250);return()=>{active=false;window.clearTimeout(timer);};},[field.target_entity,query,token]);return <div className="relation-field">{error&&<div className="error" role="alert">{error}</div>}<input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search related records" aria-label={`${field.label??field.code} search`}/><select value={value} onChange={(e)=>onChange(e.target.value)} disabled={busy} aria-label={field.label??field.code}><option value="">{busy?'Loading…':'Select a record'}</option>{items.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select>{value&&<small className="muted">Selected: {value.slice(0,8)}…</small>}</div>;}

function EntityPage({token,role,entityCode,onLogout,onBack}:{token:string;role:string;entityCode:string;onLogout:()=>void;onBack:()=>void}){const [metadata,setMetadata]=useState<Metadata|null>(null);const [records,setRecords]=useState<RecordItem[]>([]);const [form,setForm]=useState<Record<string,string|boolean>>({});const [busy,setBusy]=useState(true);const [error,setError]=useState<string|null>(null);const fields=useMemo(()=>metadata?.definition.fields??[],[metadata]);const permissions=metadata?.definition.permissions;const allowed=(action:PermissionAction)=>role==='admin'||permissions?.[role==='member'?'member':'admin']?.includes(action)===true;
  async function load(){setBusy(true);setError(null);try{const [meta,items]=await Promise.all([api<Metadata>(`/metadata/entities/${entityCode}`,token),api<RecordItem[]>(`/entities/${entityCode}/records`,token)]);setMetadata(meta);setRecords(items);}catch(err){setError(err instanceof Error?err.message:'Unable to load entity');}finally{setBusy(false);}}
  useEffect(()=>{void load();},[entityCode,token]); function setField(field:Field,value:string|boolean){setForm((current)=>({...current,[field.code]:value}));} function serializeField(field:Field,value:string|boolean):unknown{if(field.type==='integer')return Number(value);return value;}
  async function create(){setError(null);try{const data:Record<string,unknown>={};for(const field of fields){if(field.type==='boolean')data[field.code]=Boolean(form[field.code]);else if(form[field.code]!==undefined&&form[field.code]!=='')data[field.code]=serializeField(field,form[field.code]);}await api(`/entities/${entityCode}/records`,token,{method:'POST',body:JSON.stringify({data})});setForm({});await load();}catch(err){setError(err instanceof Error?err.message:'Unable to create record');}}
  async function remove(record:RecordItem){setError(null);try{await api(`/entities/${entityCode}/records/${record.id}`,token,{method:'DELETE'});setRecords((current)=>current.filter((item)=>item.id!==record.id));}catch(err){setError(err instanceof Error?err.message:'Unable to delete record');}}
  return <main className="shell"><header className="hero"><div><p className="eyebrow">2TO / EOS · {role}</p><h1>{metadata?.definition.name??entityCode}</h1><p className="muted">{entityCode}</p></div><div className="actions"><div className="pill">{metadata?`v${metadata.version} · Published`:'Loading metadata'}</div><button className="secondary" onClick={onBack}>Entities</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>{error&&<div className="error" role="alert">{error}</div>}{metadata&&<section className="card"><h2>New record</h2><div className="grid">{fields.map((field)=><label key={field.code}><span>{field.label??field.code}{field.required?' *':''}</span>{field.type==='boolean'?<input type="checkbox" checked={Boolean(form[field.code])} onChange={(e)=>setField(field,e.target.checked)}/>:field.type==='relation'?<RelationField token={token} field={field} value={String(form[field.code]??'')} onChange={(value)=>setField(field,value)}/>:<input type={field.type==='integer'||field.type==='decimal'?'number':field.type==='date'?'date':'text'} value={String(form[field.code]??'')} onChange={(e)=>setField(field,e.target.value)}/>}</label>)}</div>{allowed('create')&&<button disabled={busy||fields.length===0} onClick={()=>void create()}>Create record</button>}</section>}{metadata&&<section className="card"><div className="section-head"><h2>Records</h2><button className="secondary" onClick={()=>void load()}>Refresh</button></div>{records.length===0?<p className="muted">No records yet.</p>:<div className="table-wrap"><table><thead><tr><th>ID</th>{fields.map((field)=><th key={field.code}>{field.label??field.code}</th>)}<th/></tr></thead><tbody>{records.map((record)=><tr key={record.id}><td>{record.id.slice(0,8)}…</td>{fields.map((field)=><td key={field.code}>{String(record.data[field.code]??'')}</td>)}<td>{allowed('delete')&&<button className="danger" onClick={()=>void remove(record)}>Delete</button>}</td></tr>)}</tbody></table></div>}</section>}</main>;
}

function CatalogPage({token,role,onSelect,onLogout,onCreate}:{token:string;role:string;onSelect:(code:string)=>void;onLogout:()=>void;onCreate:()=>void}){const [entities,setEntities]=useState<MetadataSummary[]>([]);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(true);async function load(){setBusy(true);setError(null);try{setEntities(await api<MetadataSummary[]>('/metadata/entities',token));}catch(err){setError(err instanceof Error?err.message:'Unable to load entity catalog');}finally{setBusy(false);}}useEffect(()=>{void load();},[token]);return <main className="shell"><header className="hero"><div><p className="eyebrow">2TO / EOS</p><h1>Entity workspace</h1><p className="muted">Choose a published metadata entity. The UI is generated from its definition.</p></div><button className="secondary" onClick={onLogout}>Sign out</button></header>{error&&<div className="error" role="alert">{error}</div>}{role==='admin'&&<MetadataStudio token={token} defaultCode={DEFAULT_ENTITY} onCreated={onSelect}/>}<section className="card"><div className="section-head"><h2>Published entities</h2><div className="actions"><span className="pill">{entities.length} available</span>{role==='admin'&&<button onClick={onCreate}>New entity</button>}<button className="secondary" onClick={()=>void load()}>Refresh</button></div></div>{busy?<p className="muted">Loading catalog…</p>:entities.length===0?<p className="muted">No published entities exist yet.</p>:<div className="catalog-grid">{entities.map((entity)=><button className="entity-card" key={entity.code} onClick={()=>onSelect(entity.code)}><strong>{entity.name}</strong><span>{entity.code}</span><small>v{entity.version} · {entity.field_count} fields</small></button>)}</div>}</section></main>}

function App(){const [session,setSession]=useState<Session|null>(()=>sessionFromStorage());const [entityCode,setEntityCode]=useState<string|null>(DEFAULT_ENTITY||null);const [studioOnly,setStudioOnly]=useState(false);const [hydrating,setHydrating]=useState(Boolean(session));useEffect(()=>{if(!session){setHydrating(false);return;}if(session.user_id&&session.role){setHydrating(false);return;}let active=true;void api<{user_id:string;tenant_id:string;role:string;email:string}>('/auth/me',session.access_token).then((me)=>{if(active)setSession((current)=>current?{...current,user_id:me.user_id,tenant_id:me.tenant_id,role:me.role}:current);}).catch(()=>{if(active){localStorage.removeItem(TOKEN_KEY);setSession(null);setEntityCode(null);}}).finally(()=>{if(active)setHydrating(false);});return()=>{active=false;};},[session]);function authenticated(data:Session){localStorage.setItem(TOKEN_KEY,data.access_token);setSession(data);setHydrating(false);}function logout(){localStorage.removeItem(TOKEN_KEY);setSession(null);setEntityCode(null);setStudioOnly(false);}if(hydrating)return <main className="shell"><section className="card"><p className="muted">Restoring your workspace…</p></section></main>;if(!session)return <AuthScreen onAuthenticated={authenticated}/>;if(studioOnly&&session.role==='admin')return <main className="shell"><header className="hero"><div><p className="eyebrow">2TO / EOS</p><h1>Metadata Studio</h1></div><button className="secondary" onClick={()=>setStudioOnly(false)}>Back</button></header><MetadataStudio token={session.access_token} defaultCode={DEFAULT_ENTITY} onCreated={(code)=>{setStudioOnly(false);setEntityCode(code);}}/></main>;if(entityCode)return <EntityPage token={session.access_token} role={session.role} entityCode={entityCode} onLogout={logout} onBack={()=>setEntityCode(null)}/>;return <CatalogPage token={session.access_token} role={session.role} onSelect={(code)=>{setEntityCode(code);setStudioOnly(false);}} onLogout={logout} onCreate={()=>setStudioOnly(true)}/>;}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
